### ISSUE TITLE
Different Example Vocabularies/Blocks

### ISSUE THREAD

**Issue by djbrooke** [gdcc/dataverse-external-vocab-support#4]
In a recent demo it was suggested that the test/demo block be renamed to something different than "cvocDemoMetadata" in order to make demos more aligned with actual use. If this get prioritized I'm happy to provide some suggestions!

**Comment by qqmyers** [comment]
suggest away

**Comment by qqmyers** [comment]
current names at https://github.com/gdcc/dataverse-external-vocab-support/blob/main/examples/metadatablocks/cvocdemo.tsv

This tsv also has updates to fix the displayOrder of fields (some fields had the same #, which messed up the listing of fields in the Dataverse Edit/General Info page, makes the creator/ORCID field facetable (better for testing), removes the vocab name field from being advanced searchable (since the scripts don't affect it which is confusing in an example).

**Comment by djbrooke** [comment]
@qqmyers - I think this is fine! Thanks for making the updates.
